backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "anime"
    label: "Anime"
    label_singular: "Anime"
    extension: "json"
    format: "json"
    files:
      - file: "anime.json"
        label: "Anime List"
        name: "anime"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "text" }
          - { name: "banner", label: "Banner", widget: "image" }
          - { name: "youtube", label: "YouTube Link", widget: "string" }
          - { name: "download", label: "Download Link", widget: "string" }
          - { name: "rating", label: "Rating", widget: "number" }