backend:
  name: git-gateway
  branch: main

media_folder: "uploads" # jaha images save hongi
public_folder: "/uploads"

collections:
  - name: "anime"
    label: "Anime List"
    label_singular: "Anime"
    folder: "content/anime"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "banner", label: "Banner Image", widget: "image" }
      - { name: "youtube", label: "YouTube Link", widget: "string" }
      - { name: "download", label: "Download Link", widget: "string" }
      - { name: "rating", label: "Rating", widget: "number", value_type: "float", min: 0, max: 10 }