backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "anime"
    label: "Anime"
    folder: "anime"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "YouTube Link", name: "youtube", widget: "string" }
      - { label: "Download Link", name: "download", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number" }